<div id="content">
		<div class="title">
			<h2>Benvenuto <span class="byline">in Eventseeker</span></h2>
		</div>
		<a  href="#" class="image image-full"><img id="centralimg" src="css/images/pic02.jpg" alt="" /></a>
		<p>Eventseeker.com &egrave un portale che raccoglie notizie di Eventi e Appuntamenti dagli utenti registrati.
L'utilizzo &egrave gratuito ed &egrave sufficiente la registrazione, semplice, veloce e gratuita.
Ogni utente registrato dispone di una propria home page con gli eventi acquistati, allo scopo di costituire un vero e proprio archivio personale.</p>
	<p><a href="Documentazione del sito.pdf">Documentazione del sito</a></p>
	</div>
	<div id="sidebar">
		<h2 class="title">Prossimi Eventi</h2>
		<ul class="style2">
			<li id="ancora1"  class="first">
				<h3><a onMouseOver="displayImg1();" onmouseleave="displayImgDefault();">Vasco Rossi in tour</a></h3>
				<p>Dopo quasi due anni di silenzio, torna il Komandante! I biglietti per Vasco Rossi sono ora disponibili, con il Blasco che torna a calcare i palchi italiani per un nuovo tour che si preannuncia sold out</p>
			</li>
			<li id="ancora2">
				<h3><a onMouseOver="displayImg2();" onmouseleave="displayImgDefault();" href="#">Laura Pausini in Ancona </a></h3>
				<p>Laura Pausini, cantante e cantautrice di calibro internazionale, è tornata con il tour Laura Pausini 2013 che ha tutte le premesse per essere un evento da non perdere! Acquista ora i biglietti</p>
			</li>
			<li id="ancora3">
				<h3><a onMouseOver="displayImg3();" onmouseleave="displayImgDefault();" href="#">Aida all'Arena di Verona</a></h3>
				<p>Opera lirica in quattro atti di Giuseppe Verdi su libretto di Antonio Ghislanzoni, tratto da uno spunto di Auguste Mariette, rielaborato da Camille Du Locle in collaborazione con Verdi.</p>
			</li>
		</ul>
	</div>
</div>