<div id="page" class="container">
	<div id="content">
		<div class="title">
			<h2>Sede <span class="byline">Principale</span></h2>
		</div>
		
		<iframe width="590" height="525" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"  src="http://maps.google.it/maps?f=q&amp;source=s_q&amp;hl=it&amp;geocode=&amp;q=Via+Brecce+Bianche,+12,+Ancona&amp;aq=0&amp;sll=41.442726,12.392578&amp;sspn=23.377375,53.657227&amp;ie=UTF8&amp;hq=&amp;hnear=Via+Brecce+Bianche,+12,+60131+Ancona,+Marche&amp;z=14&amp;ll=43.581248,13.515684&amp;output=embed"></iframe>
	</div>
<div id="sidebar1">
		<h2 class="title">Descrizione generale</h2>	
		<p>Eventseeker.com &egrave un portale che raccoglie notizie di Eventi e Appuntamenti dagli utenti registrati.
L'utilizzo &egrave gratuito ed &egrave sufficiente la registrazione, semplice, veloce e gratuita.
Ogni utente registrato dispone di una propria home page con gli eventi acquistati, allo scopo di costituire un vero e proprio archivio personale.</p>
		
</div>
</div>