<div id="page" class="container">
	<div class="title">
			<h2>The Films <span class="byline"> In Our Catalog</span></h2>
		</div>
		
		<li>
		<?php foreach ($this->Films as $film) :?>
		<div class="prod">
		  
		        <div class=sidebarimg> <?php echo $this->eventImg($film->film_image, array('class' => 'imagefrm')) ?></div>
		        <div class="info">		      
		          <?php echo'<h1 class="title"> ' . $film->name . '</h1>' ?>
		          <?php echo'<h4 class="title"> ' . $film->date . '</h4> Inizio:'.$film->start_time.'</br>' ?>
		          <?php echo'<h4 class="title">Luogo: ' . $film->location . '</h4>'?>
		          <?php echo '<p class="meta">' . $film->description . '</p>' ?>
		        </div>
		        <div class="pricebox">
		          <?php echo'prezzo intero:'. $film->price.'€' ?>
		          <?php echo'prezzo ridotto:'. $film->price_ridotto.'€</br>' ?>
		        </div>
		        </div>
		 
		  
		
<?php endforeach ?>
</div>