<div id="page" class="container">
	<div class="title">
			<h2>Evento<span class="byline"> selezionato</span></h2>
		</div>
		
		<?php function convertiDate($date)
							{
							$rsl = explode ('-',$date);
							$rsl = array_reverse($rsl);
							return implode($rsl,'/');
							}
					$date=convertiDate($this->event->date)
		?>
		<div class="prod">
		  
		        <div class=sidebarimg> <?php echo $this->eventImg($this->event->image, array('class' => 'imagefrm')) ?></div>
		        <div class="info">		      
		          <?php echo'<h1 class="title"> ' . $this->event->name . '</h1>' ?>
		          <?php echo'<h4 class="title"> ' . $date . '</h4> Inizio:'.$this->event->start_time.'</br>';?>
		          <?php echo'<h4 class="title">Luogo: ' . $this->event->location . '</h4>'?>
		          <?php echo '<p class="meta">' . $this->event->description . '</p>' ?>
		        </div>
		        <div class="pricebox">
		        	<?php $prices=$this->priceHelper($this->event->event_id); ?>
		        	<p>Prezzo:</p>
		        	<?php foreach ($prices as $price) {
		        		echo $price->sezione.' :'.$price->prezzo.'€'.'</br>';
						
					} echo'</br></br>'?>
		          
		        </div>
		        <?php $rec=1; ?>
		        
		        
		       
	  
		       
	  
		 
		  
		

</div>
</div>