<div id="fbox1">
		<h2 class="title">I nostri Eventi</h2>
		<p>Accedi alla nostra sezione eventi per rimanere sempre aggiornato sulle manifestazioni artistiche presenti nella tua citta. Non chiederti mai pi&ugrave cosa fare stasera. </p>
		<a href="public/ourevents" class="button">Eventi</a> </div>
	<div id="fbox2">
		<h2 class="title">Contattaci</h2>
		<ul class="style1">
			<p>Non esitare a chiedere aiuto ad uno dei nostri addetti per ottenere informazioni o per ricevere aiuto in merito aqualunque problema tu possa avere</p>
			
		</ul>
		<a href="public/Contactus" class="button">Contattaci</a> </div>
	<div id="fbox3">
		<h2 class="title">Social</h2>
		<ul class="style1">
			<li class="first"><a href="#">Twitter</a></li>
			<li><a href="">Facebook</a></li>
			<li><a href="">Flickr</a></li>
			<li><a href="">Google +</a></li>
		</ul>
	</div>