<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.0/jquery.min.js"></script>



<div id="page" class="container">
<div class="static">
 <div class="title">
			<h2>Compra biglietto <span class="byline">per questo evento:</span></h2>
			<h3><?php echo $this->nameEvent?>   <span><?php echo $this->dateEvent?></span></h3>
		</div>
 <p>Utilizza questa form per l'acquisto</p>
 <?php echo $this->prenotazioneForm ?>
</div>
</div>